### ISSUE TITLE
Unnecessary spaces are added between CJK characters

### ISSUE THREAD

**Issue by fiammanda** [TheJoeFin/Text-Grab#132]

**Comment by TheJoeFin** [comment]
Hello @fiammanda could you please provide a screenshot or reference website which can be used to demonstrate this behavior every time?

**Comment by fiammanda** [comment]
@TheJoeFin 
![ZLUXZ$U4UX)%L1N`4` V1(R](https://user-images.githubusercontent.com/8189264/143984765-8a0b709f-6f5c-4480-a6c2-4b4556c6e560.png)
Actually onenote ocr has the same problem, which makes it almost unusable for CJK users.

**Comment by TheJoeFin** [comment]
Thank you very much for the images. Could you also share the output of the OCR including the problematic spaces. Then a fixed version which has all the problems removed. 

Since I only speak English I'd like to collaborate with you on making a post-processing method to fix issues like these for CJK users.

**Comment by TheJoeFin** [comment]
don't add spaces when culture code family is `zh`, `ko`, `ja`

per ISO 639-1 here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
