### ISSUE TITLE
Set another language as default?

### ISSUE THREAD

**Issue by ayanamist** [TheJoeFin/Text-Grab#187]
When using Fullscreen Grab, it will let me choose use which language like below:
![image](https://user-images.githubusercontent.com/406779/188801972-507c70b5-4fc4-486a-b0e2-b75f0bc597e0.png)
I want to always use `zh-Hans-CN` so i have to switch it again and again.
Also when using Grab Frame, i can't switch it and it always use `en-US`
I read the source code and found that, it lists all input languages, and using first one when using Grab Frame.
https://github.com/TheJoeFin/Text-Grab/blob/d3dd4cd2410406f16637e9c8af9e3be94e0011d2/Text-Grab/Utilities/ImageMethods.cs#L373
Can it be given an setting to choose a default value?
Thank you.

**Comment by TheJoeFin** [comment]
For the Fullscreen Grab, you can press the number keys to quickly change which language is selected, 1 for the first, 2 for the second, etc. 

I have been hesitant to include a setting for choosing a default language which is different than the keyboard option because there is no API to detect changes and it is another layer of settings checking and complexity.

For changing the language on the Grab Frame, if you change your keyboard language (Win + Space) it will change the language Text Grab uses for OCR. But since there is a drop down for the Fullscreen Grab, there should be one for Grab Frame as well.

**Comment by ayanamist** [comment]
Can you make it remember the last language i used, which will save my mind to switch the language before start capture. It always ignore CJK chars before i realize i haven't switch the language.

Nearly all [CJK](https://en.wikipedia.org/wiki/CJK_characters) users have two language installed, one is US keyboard (en_US) which used to typing URL, coding, gaming, and the other one is CJK input method used to type CJK chars. You can see one example in wikipedia https://en.wikipedia.org/wiki/File:TypingChineseCharactersWithCangjieGedit383Ubuntu1310Screencast.webm 
So usually it's in `en_US` language when using Text-Grab, and it is very annoying to remember switch language to let Text-Grab use CJK engine but not english engine.

**Comment by TheJoeFin** [comment]
Saving the last set language is a good idea. I'll do that.
