### ISSUE TITLE
Chinese/Multilingual Support

### ISSUE THREAD

**Issue by cjbarth** [TheJoeFin/Text-Grab#19]
Is there a desire to have support for multiple languages? It appears that the API that you are using supports that: https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr.ocrengine?view=winrt-19041#properties

I see that you are just using the language returned by `InstalledLanguages.FirstOrDefault()`. If you are interested in multi-lingual support, do you have any ideas of how you'd like to see that support added? I might be able to contribute a PR. Initially, the thing that comes to mind is using the current keyboard setting as the language.

**Comment by TheJoeFin** [comment]
Thanks for the issue, yes I plan to add the ability to set the language from a settings window. I chose to use the first installed language because that can drive things within Windows 10 like date/time.

Once I get the settings pane added I would be interested in accepting PRs. I'll circle back to this issue and let you know when the settings window is in the main branch. I would like to have the settings window added before my next release; before the end of the month.

**Comment by TheJoeFin** [comment]
@cjbarth Text Grab now uses the currently selected language as the language for the OCR engine. Does this meet your request here or would you prefer to have a separate setting within Text Grab to set the language?

**Comment by laicasaane** [comment]
Hi, I would like to have a separate setting. I don't want to change Windows language just for OCR.

**Comment by TheJoeFin** [comment]
Just to be clear of how the implementation will be done. Text Grab relies on the installed Windows languages to do the OCR. You don't have to change the Windows display language, just the current keyboard language (Win + Space). 

To change the Text Grab language you'd have to open settings then pick from a list of the installed languages. I can see how this would be helpful so I'll work on adding it, but I just wanted to be clear about how it will work in the future, and how Text Grab works now.

**Comment by laicasaane** [comment]
> just the current keyboard language (Win + Space)

I've tested this option but OCR gave me wrong result so I thought Text Grab language was still English.

> I just wanted to layout how it will work in the future, and how Text Grab works now

How about an option to let us choose when we want to use Win+Space or the language setting?

**Comment by zybexXL** [comment]
You need to have the Language Pack installed in Windows ("Add a Language"), not just the Keyboard layout. Then you can select with Win+Space and it works.
I see no point in implementing a second menu that does exactly the same as Win+Space. Since TextGrab uses the Windows API, you would still need to install the Language Pack anyway for it to work.

**Comment by TheJoeFin** [comment]
Based upon the discussion here and trying to keep Text Grab simple I'm not planning on adding another setting to select language. To perform OCR the language must be installed and switching language with Win+Space is quick and easy to do.

**Comment by cjbarth** [comment]
> @cjbarth Text Grab now uses the currently selected language as the language for the OCR engine. Does this meet your request here or would you prefer to have a separate setting within Text Grab to set the language? 

Yes

**Comment by Ask1n** [comment]
@TheJoeFin hmm, I thought you can install a language pack without adding it to the language bar
