### ISSUE TITLE
Suggestion: Add option for a ShortCut key

### ISSUE THREAD

**Issue by TheAndyMac** [TheJoeFin/Text-Grab#30]
Would love to be able to call up the app in "grab" mode using a keyboard shortcut, much in the way that Win+Shift+S opens up the graphics screen clip. Ideal if this could be switched on/off, custom selected and maybe having a default key such as Win+Ctrl+S (which seems to be unused by Windows and things like PowerToys).

**Comment by TheJoeFin** [comment]
Hello @TheAndyMac, this feature was intentionally not done because it would require Text Grab to have a background task running all the time. However Windows has a built-in way to activate any application with a keyboard shortcut. 

Pin Text Grab to the Taskbar and move it to the 2nd position. They press Winkey + 2
This will launch Text Grab, and when it is complete it will shut down. 

I'm looking into adding a background process option which can be enabled, but for now pinning to the Taskbar or using a tool like AutoHotKey is the best way to activate via the keyboard.

**Comment by TheAndyMac** [comment]
Thanks, and I understand.
Regards
Andrew Macaulay
