### ISSUE TITLE
Multi Monitor Support

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Text-Grab#5]

**Comment by lupalby** [comment]
Just started using the app and it's fantastically simple and effective. I immediately noticed the lack of multi monitor support, and that for me is a big impediment since I have 2 monitors and the embedded one of my laptop is not where I usually display what I am working on.
I know I can simply move the window on the other screen before using Text Grab, but it would be awesome if it supported multi monitor.
Keep up the great work! Thank you for sharing this app with the world

**Comment by TheJoeFin** [comment]
Initial multi-monitor support is working. Although there are still issues when different monitors have different scaling factors.

**Comment by lupalby** [comment]
Yes, I can confirm that with the last update I do see the grayed area now covers both monitors, but if I select something in the second monitor it seems to read from a different area rather than the one I selected, with a predictable offset. How are you currently handling 2 monitors? and how does scaling affect the mechanism? I have 125% on the primary monitor (small 14" laptop screen) and 100% on the second (20" desktop monitor)

**Comment by TheJoeFin** [comment]
Multi monitor support with different monitors with different DPI scaling factors are messy. From what I've figured out by experimentation The scaling of the primary monitor is used for the entire application. I have not found a straightforward way of getting the per screen DPI scaling of each window. I am still working on it.

**Comment by jdrch** [comment]
Still doesn't work more than 2 monitors. I have a [triple monitor setup](https://github.com/jdrch/Hardware/blob/master/Dell%20XPS%208500%20Special%20Edition.md#external-monitors) and Text Grab works only on the 1st 2 monitors when invoked. Doesn't show up on the 3rd.

I could be wrong but it seems like TG needs to be able to dynamically detect all connected monitors.

**Comment by TheJoeFin** [comment]
Text Grab does try to dynamically detect and put a window on each screen. Can you post a screen shot of your monitor layout so I can attempt to better replicate your setup and try to debug the problem. Also please include monitor resolution and scaling factors.

Like this:
1.) 1920 x 1080 scale: 100%
2.) 1920 x 1080 scale: 100%
![image](https://user-images.githubusercontent.com/7809853/106031316-be5b1a80-6094-11eb-9e84-32a438dd8a1e.png)

**Comment by jdrch** [comment]
1. 3840x2160 scale: 100%
2. Same as 1
3. 2560x1440 scale 100%

![Presentation1](https://user-images.githubusercontent.com/1056759/106033092-efd4e580-6096-11eb-80bd-10d3871a03bb.png)

**Comment by TheJoeFin** [comment]
I have submitted 1.5 to the store which should fix this issue. If it does not, feel free to reopen the issue.
